### ISSUE TITLE
The plugin seems to prevent the content from changing when switching to source and back?

### ISSUE THREAD

**Issue by dryoma** [w8tcha/CKEditor-TextSelection-Plugin#31]
Hi again,

Just tried the code from the master tree, and it seems with the plugin removes the contend entered in the wysiwyg mode.

- Add the plugin.
- Do something in WYSIWYG.
- Switch to Source - the changes are discarded.
- Changes made in the Source mode are kept.

On top of that, it doesn't seem to update between page reloads. Seem like some problem with caching to localStorage.

Tried in CKEditor 4.7.3 with a custom setup, and the latest 4.9.2 (clean setup, full bundle). This screencast has been made with the latter one on the sample page (it also has the utility span elements kept).

![textselection-mode-switch](https://user-images.githubusercontent.com/11942776/40971152-403ca3ac-68ef-11e8-97d4-2cb08b87c1f1.gif)

Can this be me doing something wrong?
Thanks!

**Comment by roadlittledawn** [comment]
i encountered the same issue. it looked like the original html string that's stored in local storage wasn't being updated, so it always replaces editor content with that original string. 

i ended up using the code prior to the local storage commit and it works well. i had to force clear cache by changing the timestamp in the *ckeditor/ckeditor/ckeditor.js* file.

haven't looked lately, but @w8tcha said he added some checks since i reported.

my issue FWIW: https://github.com/w8tcha/CKEditor-TextSelection-Plugin/issues/29

**Comment by dryoma** [comment]
Yeah, had to downgrade too (to 1.0.6, which has the bug described in #28 ).

**Comment by w8tcha** [comment]
Could you please try with the latest commit? I replaced the local storage function.

In my initial tests it appears to be working

**Comment by dryoma** [comment]
Yes, the fix worke, thank you!
Sorry again to have taken so long to respond.
